num = int(input('Enter any number: '))
flt = input("Enter any float number: ")
print(num + flt)
print(num - flt)
print(num  - flt)
print(num  * flt)
print(num  / flt)
print(num  // flt)
print(num  % flt)
print(num  ** flt)