car = input("Enter your car model : ")
car_color = input("Your cars color : ")
car_price = int(input("whats your cars final price ? "))
car_age = int(input("whats the cars year ?: "))
print("the cars model is " + car + " its has a nice " + car_color + " it was made in " + str(car_age) + " its a really good car so the final price is " + str(car_price))